### ISSUE TITLE
Any idea why bluetooth is not working?

### ISSUE THREAD

**Issue by soulomoon** [scottsanett/M5510-4K-High-Sierra-Installation#3]
Any idea why bluetooth is not working, really want to upgrade to High Sierra, but a frequently bluetooth user.

**Comment by solvar0719** [comment]
No idea yet. The current situation is bluetooth functions seemingly well right after startup; it finds devices around it just fine. But once I attempted to connect it to another bluetooth device (my android phone in my case) and send files between devices, the connection is lost, and I'm not able to turn bluetooth off again. I was never a heavy bluetooth user so I don't know the situation with Sierra, but I did use it with Apple SmartTrackpad once and it worked well with no glitches. I guess this problem is High Sierra only.

**Comment by solvar0719** [comment]
@soulomoon Turns out I set one of the bcm related kextToPatch to `disabled=YES`. I've now set it to `NO` and now it __sort of__ works. I can now send files between devices and it works fine after waking up from sleep, with the premise that I do NOT attempt to turn it off. It's not just that I can't (turning it off in the menubar or in System Preferences doesn't work). File transfer doesn't work either after I attempted it.

**Comment by soulomoon** [comment]
It still did not find my device, it was perfectly fine in 10.12.6 though (BCM 94352Z)

\-----------------
turns out it crash 
```
    0x7fff4196b000 -     0x7fff41994ffb  com.apple.CoreBluetooth (1.0 - 1) <942F88A5-AD68-3359-90D5-6F1A3311C51A> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff4443b000 -     0x7fff4453effb  com.apple.Bluetooth (6.0.0 - 6.0.1f1) <7C3FBAE9-F2A8-319E-88D9-16250E0B36F9> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
```

But it actually appears in the USB bus, but Hardware -> Bluetooth is empty, some how it does not recognize it
```
BCM20702A0:

  Product ID:	0x216f
  Vendor ID:	0x0a5c  (Broadcom Corp.)
  Version:	1.12
  Serial Number:	346895EDA45A
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Broadcom Corp
  Location ID:	0x14300000 / 1
  Current Available (mA):	500
  Extra Operating Current (mA):	0
```

**Comment by soulomoon** [comment]
Turns out the BrcmPatchRAM2.kext or BrcmFirmwareData.kext using here are not compatible with brcm94352Z(aka dell 1560),
And the two patch is not needed in high sierra
