### ISSUE TITLE
Question about README

### ISSUE THREAD

**Issue by soulomoon** [scottsanett/M5510-4K-High-Sierra-Installation#4]
> This has already been achieved by using CoreDisplayFixup.kext and Lilu.kext (both included in the repo). Plus, the kexts don't break copy && paste, while the patch below does.

What does it mean by do the patch, below break copy && paste, since the copy && paste is working normal in the finder though I have ran that patch?

**Comment by solvar0719** [comment]
Have you ever un-patched it by any chance? That was written some time ago when applying the pixel clock patch did break copy and paste, as in you can't copy and paste anywhere including Finder. It might have been magically fixed somehow if you have never un-patched it. There was some (pure) speculation that the break was because of a security mechanism that checks the integrity of system files. The idea is do not apply the patch when there is the solution of CoreDisplayFixup and Lilu, which doesn't permanently modify system files.

**Comment by soulomoon** [comment]
Thanx for the explanation, I am sure that the parched is on because every time with the system update I have to reapply it, maybe it’s an magically fixed or that I have applied another patch that enable the copy and paste.
